version: "3.9"

services:
  fast_api:
    container_name: fast_api_api
    build:
      context: ./fast_api
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M

      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8081:8080"
  flask:
    container_name: flask_api
    build:
      context: ./flask
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8082:8081"

  fiber:
    container_name: fiber_api
    build:
      context: ./fiber
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 500M
        reservations:
          cpus: '0.01'
          memory: 100M
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "8083:8082"

  comparison:
    container_name: comparison_script
    build:
      context: ./comparison
      dockerfile: ./Dockerfile
    deploy:
      resources:
        limits:
          cpus: '0.1'
      restart_policy:
        condition: on-failure
        max_attempts: 2
    volumes:
      - ./comparison/results:/app/results
    depends_on:
      - fiber
      - flask
      - fast_api